#!/usr/bin/env python3
import argparse
import shlex
import sys
import os


# Protocol converter | subcat -> SUBCAT
if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog="subcat",
                                     description="Converts simple shell commands to the protocol SUBCAT command.")
    parser.add_argument('path', metavar='PATH', type=str, nargs='?', default='',
                        help="Path of the subcategory to switch to or create if it does not already exist")
    parser.add_argument('--advanced', dest='adv', action='store_true',
                        help='Mark this as advanced information')
    args = parser.parse_args()
    if "HOST_VERSION" in os.environ:
        print("SUBCAT %s %s" % ("ADV" if args.adv else "BAS", shlex(args.path)))
    else:
        print("Change to %s" % (shlex.quote(args.path)))
