#!/bin/bash

type="BAS"
subcat="."

while (( "$#" )); do
  case "$1" in
    --advanced)
      type="ADV"
      shift
      ;;
    --subcat)
      subcat=$2
      shift 2
      ;;
    --) # end argument parsing
      shift
      break
      ;;
    *)
      break
      ;;
  esac
done

echo -n "VALUE $advanced SUBCAT $subcat \"$1\" "
shift

while (( "$#" )); do
  echo -n "\"$1\""
  shift
done

echo

